version: "3.7"
services:
  chaperoo-client:
    image: horners/chaperoo-client:${app_version}
    build: .
    ports:
      - target: 80
        published: 80
    depends_on:
      - chaperoo-service    
  chaperoo-service: 
    image: jordangrindrod/chaperoo-service
    depends_on: 
      - chaperoo-db
  chaperoo-db:
    image: jordangrindrod/chaperoo-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  jenkins:
    image: jenkins/jenkins:latest
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
